# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: ultralytics_yolo_example
description: "Demonstrates how to use the ultralytics_yolo plugin."
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  image_picker: ^0.8.7
  path_provider: ^2.0.0
  archive: ^3.0.0
  http: ^1.0.0
  google_mlkit_text_recognition: ^0.13.0

  ultralytics_yolo:
    path: ../

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  # flutter_image_compress: ^2.4.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  dio: ^5.9.0
  hive: ^2.2.3
  lottie: ^3.3.0
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  validatorless: ^1.2.5
  flutter_staggered_grid_view: ^0.7.0
  ntp: ^2.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_bluetooth_printer: 2.19.0
  flutter_bluetooth_printer_platform_interface: ^0.0.7
  shared_preferences: ^2.3.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
    - assets/logo.png
    - assets/applogo.png
    - assets/files/json/
    - assets/icons/detail_kendaraan/
    - assets/icons/input/
    - assets/icons/misc/
    - assets/icons/info/
    - assets/icons/side_menu/
    - assets/images/logo/
    - assets/images/illustration/
    - assets/images/layanan/
    - assets/images/accent/
    - assets/images/verifikasi/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/applogo.png"
