# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Documentation rules
    # - public_member_api_docs  # Disabled for now
    - sort_pub_dependencies

    # Style rules
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    avoid_print: warning
    public_member_api_docs: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
